### ISSUE TITLE
Blue Flashes

### ISSUE THREAD

**Issue by CollegeZombie** [LuanKovacs/LittleMatchGirlGame#14]
**Describe the bug**
There is the occasional flash of blue light when using bonfires, it is bright but might not happen during the build.

**To Reproduce**
1. Go to the bonfire in the forest.
2. light the bonfire
3. get blinded by the light, revved up like a deuce

**Expected behavior**
you shouldn't see the blue light

**Comment by ti-tyme** [comment]
I think this is mostly likely a unity glitch, hopefully it will disappear once the game is built.

**Comment by ti-tyme** [comment]
I talked to brad about it and this is just a unity thing that will go away after building so I'm gonna close this.
