### ISSUE TITLE
[UPDATE, NOW WITH CAMERA PROBLEMS] I've fallen over and can get back up

### ISSUE THREAD

**Issue by CollegeZombie** [LuanKovacs/LittleMatchGirlGame#35]
**Describe the bug**
you can fall over if you die near the end of the game

**To Reproduce**
1. Go to the final area
2. die
3. if the spawn in falling stutters a little then the player can now fall over when walking

**Expected behavior**
you shouldn't be able to fall over like that, the player while running should stay upright

**Additional context**

**Comment by Zidphoid** [comment]
Issue has changed
Player now falls over and stays on the ground instead of getting up.
The camera also appears to get stuck on Gales animation.
