### ISSUE TITLE
Bonfire Stops healing if match is lit

### ISSUE THREAD

**Issue by Zidphoid** [LuanKovacs/LittleMatchGirlGame#7]
**Describe the bug**
If you light a match at/in the vicinity of the bonfire, when the match goes out your health starts to deteriorate. Re-approaching the bonfire appears to not always heal after doing this as well. 

**To Reproduce**
1. Approach Bonfire
2. Light Match
3. When Match goes out health goes down
4. Leaving the vicinity of the bonfire and returning sometimes fixes the bonfire aoe healing but as to what the distance is to leave, I am uncertain,
**Expected behavior**
Health should continue to remain at 100 while near the bonfire. Lighting a match should not restart the death counter

**Comment by ti-tyme** [comment]
Yes, if you approach a bonfire fire with a lit match once you leave your health will start depleting even if you match stick is still alight.
